version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
    - checkout
    - restore_cache:
        keys:
          - dotnet-packages-v1-{{ checksum "./Hassie.ConcussionEngine.Engine/Hassie.ConcussionEngine.Engine.csproj" }}
    - run:
        name: "Fetch dependencies"
        command: dotnet.exe restore
    - save_cache:
        paths:
          - C:\Users\circleci\.nuget\packages
        key: dotnet-packages-v1-{{ checksum "./Hassie.ConcussionEngine.Engine/Hassie.ConcussionEngine.Engine.csproj" }}
    - run:
        name: "Build Engine"
        command: dotnet build "./Hassie.ConcussionEngine.Engine/Hassie.ConcussionEngine.Engine.csproj" -c Release
    - run:
        name: "Build Pong"
        command: dotnet build "./Hassie.ConcussionEngine.Pong/Hassie.ConcussionEngine.Pong.csproj" -c Release
    - run:
        name: "Run Tests"
        command: dotnet.exe test
