version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
    - checkout
    - restore_cache:
        keys:
          - dotnet-packages-v1-{{ checksum "./Hassie.ConcussionEngine.Engine/Hassie.ConcussionEngine.Engine.csproj" }}
    - run:
        name: "Fetch dependencies"
        command: nuget restore "Concussion Engine.sln"
    - save_cache:
        paths:
          - C:\Users\circleci\.nuget\packages
        key: dotnet-packages-v1-{{ checksum "./Hassie.ConcussionEngine.Engine/Hassie.ConcussionEngine.Engine.csproj" }}
    - run:
        name: "Build Engine"
        command: msbuild "Hassie.ConcussionEngine.Engine\Hassie.ConcussionEngine.Engine.csproj"
    - run:
        name: "Build Tests"
        command: msbuild "Hassie.ConcussionEngine.Tests.Engine\Hassie.ConcussionEngine.Tests.Engine.csproj"
    - run:
        name: "Run Tests"
        command: mstest /testcontainer:"Hassie.ConcussionEngine.Tests.Engine\Hassie.ConcussionEngine.Tests.Engine.csproj\bin\Debug\Hassie.ConcussionEngine.Tests.Engine.dll"
